### ISSUE TITLE
Popup/dialogs/clickable area at incorrect position if 'Native panel background' is disabled, especially with Floating panels

### ISSUE THREAD

**Issue by luisbocanegra** [luisbocanegra/plasma-panel-colorizer#80]
# UPDATED (2025-02-22)

In Plasma 6.2 Popups and other stuff that is drawn on the panel where changed align to the panel mask, the mask is a invisible shape that is generated form the plasma theme SVG files, which is then used by the C++ side of the panel to render the contrast and blur effect below the panel, **this new alignment works perfectly fine on stock Plasma** but causes a couple of issues that arise when we disable that mask by turning off "Native panel background"

 - CASE 1. With blur disabled after Plasma 6.2 popups appear in the wrong position, this was FIXED see [comment](https://github.com/luisbocanegra/plasma-panel-colorizer/issues/80#issuecomment-2395317761)

![image](https://github.com/user-attachments/assets/62bc5afb-15d6-48f5-8500-6784c767d890)

- CASE 2. With Blur disabled popups now align to the invisible window that is parent of the panel, which looks particularly ugly when extra margins are added to the custom panel background:

![Image](https://github.com/user-attachments/assets/786e2fb6-d91c-4cab-b2e9-60daada38936)

- CASE 3: In addition when Plasma's Floating panel feature is used the parent window is much bigger (zone in red🟥), likely to allow the panel to float/de-float freely and maybe for the detection of windows touching it, which results  in this:

![Image](https://github.com/user-attachments/assets/23d417ec-9ec7-4075-be5c-de477c21c073)

It seems to me this can only be fixed properly by accounting for the missing mask in Plasma.

If you are interested in fixing this there is more context in the comments below, please link the bug report if you do. I will try to give it a shot too but since I am a c++ newbie is not a guarantee I will be able to fix it.

Since this only affects third party plugins there is also a chance of such fix being rejected so please be patient and receptive whatever the outcome is.

**Comment by luisbocanegra** [comment]
Well turns out popups now align with the panel mask https://invent.kde.org/plasma/libplasma/-/merge_requests/1148.

Setting PlasmaCore.Types.NoBackground to the panel containmentItem https://github.com/luisbocanegra/plasma-panel-colorizer/blob/b284edbb89a335476418cf631d1a72d408c07c19/package/contents/ui/code/utils.js#L84C1-L88C2

```js
function toggleTransparency(containmentItem, nativePanelBackgroundEnabled) {
  containmentItem.Plasmoid.backgroundHints = !nativePanelBackgroundEnabled
    ? PlasmaCore.Types.NoBackground
    : PlasmaCore.Types.DefaultBackground
}
```

results in the panel creating an empty mask https://github.com/KDE/plasma-workspace/blob/c809de7c72dcc7e94eeed5a0b09cb81f5512c2e0/shell/panelview.cpp#L1363C1-L1366C28

```cpp
void PanelView::updateMask()
{
...
    if (m_backgroundHints == Plasma::Types::NoBackground) {
        KWindowEffects::enableBlurBehind(this, false);
        KWindowEffects::enableBackgroundContrast(this, false);
        setMask(QRegion()); // <- this line
```

Which successfully removes the blur and contrast (allowing the panel to be fully transparent) **but breaks the positioning of popups**.

If I don't set `PlasmaCore.Types.NoBackground` and instead try to create an empty mask from my [PanelColorizer::updatePanelMask](https://github.com/luisbocanegra/plasma-panel-colorizer/blob/b284edbb89a335476418cf631d1a72d408c07c19/plugin/panelcolorizer.cpp#L18), the panel detects it's empty and creates its own from the panel QRect instead:

```cpp
    } else {
        QRegion mask;
        QQuickItem *rootObject = this->rootObject();
        QRect screenPanelRect = geometry();
        screenPanelRect.moveTo(mapFromGlobal(screenPanelRect.topLeft()));
        if (rootObject) {
            QVariant maskProperty = rootObject->property("panelMask");
            if (static_cast<QMetaType::Type>(maskProperty.typeId()) == QMetaType::QRegion) {
                mask = get<QRegion>(std::move(maskProperty));
                const QPoint floatingTranslucentItemOffset = rootObject->property("floatingTranslucentItemOffset").toPoint();
                mask.translate(floatingTranslucentItemOffset);
            }
        }
        if (mask.isEmpty()) {
            mask = QRegion(QRect(screenPanelRect));
        }
```

Creating a 1xx mask and setting the correct position fixes the popups but now there is a bright dot on the screen and it will require compiling the C++ plugin.

```
region = QRegion();
translateX = abs(offset.x());
translateY = abs(offset.y() + rect.height() - 1);
```

[Screencast_20241004_223204.webm](https://github.com/user-attachments/assets/3a01ea73-d595-4815-a5de-2d75968ec366)

**Comment by luisbocanegra** [comment]
Upstream Bugreport https://bugs.kde.org/show_bug.cgi?id=494193
Submitted a fix at https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/4797 waiting for it to be reviewed

**Comment by luisbocanegra** [comment]
Fix has been merged 🎉 Will be available in Plasma 6.2.2 (Tue 2024-10-22)

**Comment by nikoraasu** [comment]
Has this actually been fixed? I still face this issue with the dialogs being offset. I can temporarily fix it by enabling native panel background and disabling it, but this resets when I restart my system.
![image](https://github.com/user-attachments/assets/1c342a4d-ab08-4b73-ac84-28ad46f8833c)

Using Plasma 6.2.3
Running widget version 1.2.0-1 from Aur

**Comment by mill413** [comment]
> Has this actually been fixed? I still face this issue with the dialogs being offset. I can temporarily fix it by enabling native panel background and disabling it, but this resets when I restart my system. ![image](https://private-user-images.githubusercontent.com/86488693/386949449-1c342a4d-ab08-4b73-ac84-28ad46f8833c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODE2NzEsIm5iZiI6MTczMjE4MTM3MSwicGF0aCI6Ii84NjQ4ODY5My8zODY5NDk0NDktMWMzNDJhNGQtYWIwOC00YjczLWFjODQtMjhhZDQ2Zjg4MzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA5MjkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MzRhOTU0NzkxMGI1Mzk4YWM1MDhlZjRkZmJkY2E2OTI2YmMyNDUyZjVlNDJlZjFkZDI3ZTI0ZDBmMjY4NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GZ5b0sCuFEsqt_6xTV6gZZAMt75-DfFcM5aUOMIk59Q)
> 
> Using Plasma 6.2.3 Running widget version 1.2.0-1 from Aur

Same. Plasma 6.2.3(Wayland), widget version 1.2.0-1 from AUR

**Comment by luisbocanegra** [comment]
With **Blur custom background** disabled on the panel, popups are spawned at the edge of the original blur mask (provided by the Plasma style SVG) and without **Native panel background** popups spawn at the edge of the panel "window" which seems to be bigger than the panel probably to reserve space for the SVG shadows and dodge windows features

That is why by enabling **Blur custom background** "fixes" the problem.

Also might be related to https://github.com/luisbocanegra/plasma-panel-colorizer/issues/100 ~~fix~~ workaround for that was turn the mask on and off again when the panel size changes, just like what @nikoraasu describes.

Something needs to be done to ensure the the mask is always the correct one, most likely requires another upstream patch.

**Comment by luisbocanegra** [comment]
This recording illustrates better the problem. Panel is set to floating mode and the native background disabled (Appearance tab), click issue doesn't seem to affect non-floating panels

https://github.com/user-attachments/assets/57f4f669-1b48-49dd-b28c-576c2bfa9ed4

**Comment by luisbocanegra** [comment]
I filed a bug upstream and the response was that since this is a "bug" triggered only by a third party mod (which is true) they flagged it as minor (understandable) and that is unlikely that they'll work on it themselves, but are willing to accept a fix if it doesn't cause other problems.

I tried looking at the code myself but sadly couldn't understand enough to even have a possibility of fixing it

**Comment by teksek** [comment]
I wouldn't know either, I don't even know where the code responsible for it is located 😅 So it's left to live with it for now, or use a different theme. It is what it is I guess. But it's good that at least you reported this problem and they now know about this :).
